package media

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

var exifHeader = []byte{'E', 'x', 'i', 'f', 0, 0}

// CopyJPEGExif copies the source EXIF APP1 block into a converted JPEG while
// forcing Orientation=1. This preserves capture date/camera metadata without
// making an already-rotated output rotate a second time in image viewers.
func CopyJPEGExif(src, dst string) error {
	source, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	exif, err := extractExifAPP1(source)
	if err != nil {
		return err
	}
	if len(exif) == 0 {
		return nil
	}
	patchExifOrientation(exif)
	output, err := os.ReadFile(dst)
	if err != nil {
		return err
	}
	merged, err := insertExifAPP1(output, exif)
	if err != nil {
		return err
	}
	st, _ := os.Stat(dst)
	perm := os.FileMode(0o644)
	if st != nil {
		perm = st.Mode().Perm()
	}
	tmp, err := os.CreateTemp(filepath.Dir(dst), ".mw-exif-*.jpg")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	ok := false
	defer func() {
		_ = tmp.Close()
		if !ok {
			_ = os.Remove(tmpName)
		}
	}()
	if err := tmp.Chmod(perm); err != nil {
		return err
	}
	if _, err := tmp.Write(merged); err != nil {
		return err
	}
	if err := tmp.Sync(); err != nil {
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	_ = os.Remove(dst)
	if err := os.Rename(tmpName, dst); err != nil {
		return err
	}
	ok = true
	return nil
}

func extractExifAPP1(jpeg []byte) ([]byte, error) {
	if len(jpeg) < 4 || jpeg[0] != 0xff || jpeg[1] != 0xd8 {
		return nil, errors.New("source is not a JPEG")
	}
	pos := 2
	for pos+4 <= len(jpeg) {
		if jpeg[pos] != 0xff {
			return nil, fmt.Errorf("invalid JPEG marker at %d", pos)
		}
		for pos < len(jpeg) && jpeg[pos] == 0xff {
			pos++
		}
		if pos >= len(jpeg) {
			break
		}
		marker := jpeg[pos]
		pos++
		if marker == 0xda || marker == 0xd9 {
			break
		}
		if marker == 0x01 || (marker >= 0xd0 && marker <= 0xd7) {
			continue
		}
		if pos+2 > len(jpeg) {
			return nil, errors.New("truncated JPEG segment")
		}
		segLen := int(binary.BigEndian.Uint16(jpeg[pos : pos+2]))
		if segLen < 2 || pos+segLen > len(jpeg) {
			return nil, errors.New("invalid JPEG segment length")
		}
		payload := jpeg[pos+2 : pos+segLen]
		if marker == 0xe1 && bytes.HasPrefix(payload, exifHeader) {
			return append([]byte(nil), payload...), nil
		}
		pos += segLen
	}
	return nil, nil
}

func insertExifAPP1(jpeg, exif []byte) ([]byte, error) {
	if len(jpeg) < 2 || jpeg[0] != 0xff || jpeg[1] != 0xd8 {
		return nil, errors.New("destination is not a JPEG")
	}
	if len(exif)+2 > 0xffff {
		return nil, errors.New("EXIF block is too large")
	}
	segment := make([]byte, 4+len(exif))
	segment[0], segment[1] = 0xff, 0xe1
	binary.BigEndian.PutUint16(segment[2:4], uint16(len(exif)+2))
	copy(segment[4:], exif)

	// Remove any EXIF APP1 generated by the encoder; retain non-EXIF APP1/XMP.
	clean := make([]byte, 0, len(jpeg)+len(segment))
	clean = append(clean, jpeg[:2]...)
	pos := 2
	inserted := false
	for pos < len(jpeg) {
		start := pos
		if pos+2 > len(jpeg) || jpeg[pos] != 0xff {
			clean = append(clean, jpeg[pos:]...)
			break
		}
		for pos < len(jpeg) && jpeg[pos] == 0xff {
			pos++
		}
		if pos >= len(jpeg) {
			break
		}
		marker := jpeg[pos]
		pos++
		if marker == 0xda || marker == 0xd9 {
			if !inserted {
				clean = append(clean, segment...)
				inserted = true
			}
			clean = append(clean, jpeg[start:]...)
			break
		}
		if marker == 0x01 || (marker >= 0xd0 && marker <= 0xd7) {
			clean = append(clean, jpeg[start:pos]...)
			continue
		}
		if pos+2 > len(jpeg) {
			return nil, errors.New("truncated destination JPEG")
		}
		segLen := int(binary.BigEndian.Uint16(jpeg[pos : pos+2]))
		if segLen < 2 || pos+segLen > len(jpeg) {
			return nil, errors.New("invalid destination JPEG segment")
		}
		payload := jpeg[pos+2 : pos+segLen]
		isExif := marker == 0xe1 && bytes.HasPrefix(payload, exifHeader)
		if !isExif {
			clean = append(clean, jpeg[start:pos+segLen]...)
		}
		// Place EXIF after a leading JFIF/APP0 segment, otherwise before the first
		// image metadata segment.
		if !inserted && marker != 0xe0 {
			idx := len(clean)
			if !isExif {
				idx -= pos + segLen - start
			}
			clean = append(clean[:idx], append(segment, clean[idx:]...)...)
			inserted = true
		}
		pos += segLen
	}
	if !inserted {
		clean = append(clean, segment...)
	}
	return clean, nil
}

func patchExifOrientation(exif []byte) {
	if len(exif) < 14 || !bytes.HasPrefix(exif, exifHeader) {
		return
	}
	tiff := exif[6:]
	var order binary.ByteOrder
	switch string(tiff[:2]) {
	case "II":
		order = binary.LittleEndian
	case "MM":
		order = binary.BigEndian
	default:
		return
	}
	if order.Uint16(tiff[2:4]) != 42 {
		return
	}
	off := int(order.Uint32(tiff[4:8]))
	if off < 0 || off+2 > len(tiff) {
		return
	}
	count := int(order.Uint16(tiff[off : off+2]))
	base := off + 2
	for i := 0; i < count; i++ {
		entry := base + i*12
		if entry+12 > len(tiff) {
			return
		}
		tag := order.Uint16(tiff[entry : entry+2])
		if tag != 0x0112 {
			continue
		}
		typ := order.Uint16(tiff[entry+2 : entry+4])
		n := order.Uint32(tiff[entry+4 : entry+8])
		if typ == 3 && n >= 1 {
			order.PutUint16(tiff[entry+8:entry+10], 1)
			if n == 1 {
				tiff[entry+10], tiff[entry+11] = 0, 0
			}
		}
		return
	}
}
