from __future__ import annotations

import argparse
import ctypes
import json
import os
import shutil
import subprocess
import tempfile
import time
from ctypes import wintypes
from pathlib import Path

import round11_flicker_gate as gate
import round11_flicker_gate_runner_base as runner
import round12_scroll_overlay_gate as overlay_gate
from round12_remote_header import RemoteHeaderReader

LVM_FIRST = 0x1000
LVM_GETTOPINDEX = LVM_FIRST + 39
WM_MOUSEWHEEL = 0x020A
WM_HSCROLL = 0x0114
SB_PAGERIGHT = 3
MOUSEEVENTF_LEFTDOWN = 0x0002
MOUSEEVENTF_LEFTUP = 0x0004
WHEEL_DELTA = 120

gate.user32.SendMessageW.argtypes = [
    wintypes.HWND,
    wintypes.UINT,
    wintypes.WPARAM,
    wintypes.LPARAM,
]
gate.user32.SendMessageW.restype = ctypes.c_ssize_t
gate.user32.mouse_event.argtypes = [
    wintypes.DWORD,
    wintypes.DWORD,
    wintypes.DWORD,
    wintypes.DWORD,
    ctypes.c_size_t,
]
gate.user32.mouse_event.restype = None


def terminate_process(process: subprocess.Popen[bytes] | subprocess.Popen[str]) -> None:
    if process.poll() is not None:
        return
    process.terminate()
    try:
        process.wait(timeout=5.0)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait(timeout=5.0)


def top_index(list_hwnd: int) -> int:
    return int(gate.user32.SendMessageW(list_hwnd, LVM_GETTOPINDEX, 0, 0))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--exe", required=True, type=Path)
    parser.add_argument("--evidence", required=True, type=Path)
    args = parser.parse_args()

    exe = args.exe.resolve()
    evidence = args.evidence.resolve()
    evidence.mkdir(parents=True, exist_ok=True)
    isolated = Path(tempfile.mkdtemp(prefix="mediova-round12-native-function-"))
    env = os.environ.copy()
    env["APPDATA"] = str(isolated)
    env["LOCALAPPDATA"] = str(isolated)
    env["XDG_CONFIG_HOME"] = str(isolated)

    process = subprocess.Popen(
        [str(exe), "--ui-preview=video", runner.ROUND11_SCROLL_PREVIEW_ARG],
        cwd=str(exe.parent),
        env=env,
    )
    try:
        main_hwnd = gate.find_window(process.pid, "Mediova", 20.0)
        overflow = runner.establish_real_overflow(main_hwnd)
        state = overlay_gate.native_list_state(main_hwnd)
        list_hwnd = int(state["hwnd"])

        left, top, right, bottom = [int(value) for value in state["rect"]]
        gate.user32.SetCursorPos((left + right) // 2, (top + bottom) // 2)
        gate.user32.SetForegroundWindow(main_hwnd)
        gate.user32.mouse_event(MOUSEEVENTF_LEFTDOWN, 0, 0, 0, 0)
        gate.user32.mouse_event(MOUSEEVENTF_LEFTUP, 0, 0, 0, 0)
        time.sleep(0.10)
        vertical_before = top_index(list_hwnd)
        wheel_wparam = ctypes.c_size_t(ctypes.c_uint16(-WHEEL_DELTA).value << 16).value
        wheel_lparam = ((top + bottom) // 2 & 0xFFFF) << 16 | ((left + right) // 2 & 0xFFFF)
        gate.user32.SendMessageW(list_hwnd, WM_MOUSEWHEEL, wheel_wparam, wheel_lparam)
        time.sleep(0.25)
        vertical_after = top_index(list_hwnd)
        if vertical_after <= vertical_before:
            raise RuntimeError(
                f"native mouse wheel did not move rows: before={vertical_before} after={vertical_after}"
            )

        reader = RemoteHeaderReader(process.pid)
        try:
            # Header item rectangles remain header-relative on some common-control
            # versions.  A real ListView subitem rectangle moves with the native
            # horizontal viewport, so it is a deterministic semantic signal.
            before_left = int(reader.list_subitem_rect(list_hwnd, 0, 2)[0])
            # Deliver the semantic message generated by a native horizontal
            # track page. Global cursor injection is desktop/occlusion dependent
            # and made this gate flaky even when the ListView worked correctly.
            gate.user32.SendMessageW(list_hwnd, WM_HSCROLL, SB_PAGERIGHT, 0)
            time.sleep(0.20)
            after_left = int(reader.list_subitem_rect(list_hwnd, 0, 2)[0])
        finally:
            reader.close()
        horizontal_changed = after_left < before_left
        if not horizontal_changed:
            raise RuntimeError(
                f"native horizontal page did not move ListView content: before={before_left} after={after_left}"
            )

        report = {
            "architecture": overlay_gate.NATIVE_SCROLL_ARCHITECTURE,
            "overflow": overflow,
            "list": overlay_gate.native_list_state(main_hwnd),
            "mouse_wheel_vertical_moved": True,
            "mouse_wheel_delivery": "WM_MOUSEWHEEL",
            "vertical_top_before": vertical_before,
            "vertical_top_after": vertical_after,
            "horizontal_native_page_moved": horizontal_changed,
            "horizontal_delivery": "WM_HSCROLL/SB_PAGERIGHT",
            "horizontal_subitem_left_before": before_left,
            "horizontal_subitem_left_after": after_left,
            "custom_scrollbar_window_count": 0,
        }
        (evidence / "round12-scroll-function-report.json").write_text(
            json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        print(json.dumps(report, ensure_ascii=True, separators=(",", ":")))
        return 0
    finally:
        terminate_process(process)
        shutil.rmtree(isolated, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
