<Project>
  <PropertyGroup>
    <Version>0.4.25</Version>
    <FileVersion>0.4.25.0</FileVersion>
    <AssemblyVersion>0.4.25.0</AssemblyVersion>
    <Company>FenLynn</Company>
    <Product>LaserBench</Product>
    <Copyright>Copyright © 2026 FenLynn</Copyright>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
